# permissions to do viewer spoccs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spocc-viewer-role
rules:
- apiGroups:
  - paul.blart
  resources:
  - spoccs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paul.blart
  resources:
  - spoccs/status
  verbs:
  - get
